language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2
before_script:
  - "cp config/secrets.yml.template config/secrets.yml"
  - "cp config/smtp.yml.template config/smtp.yml"
  - "cp config/ezid.yml.template config/ezid.yml"
  - "cp config/blacklight.yml.template config/blacklight.yml"
  - "cp config/database.yml.template config/database.yml"
  - "cp config/fedora.yml.template config/fedora.yml"
  - "cp config/solr.yml.template config/solr.yml"

notifications:
  email:
    - justin@curationexperts.com

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
