---
# roles/alexandria/defaults/main.yml
project_name: alexandria
project_base: /opt
marmotta_server: 127.0.0.1
deploy_user: adrl
deploy_group: adrl
minter_state_location: "{{ project_base }}/{{ project_name }}/shared/minter-state"
etd_download_root: "{{ project_base }}/download_root"
derivatives_directory: "{{ project_base }}/{{ project_name }}/derivatives"
uploads_directory: "{{ project_base }}/{{ project_name }}/uploads"
