- name: ADRL on CentOS
  hosts: all
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"

  vars:
    deploy_user: adrl
    deploy_group: adrl
    deploy_keys:
      - "{{ lookup('env', 'GH_USER') }}"

    server_name: "{{ lookup('env', 'SERVER') }}"
    project_base: /opt
    project_name: alexandria-v2
    install_path: "{{ project_base }}/install"

    rails_env: production
    rails_secret_key_base: "{{ lookup('env', 'SECRET') }}"
    config_path: "{{ project_base }}/{{ project_name }}/shared/config"

    # `tomcat` is the directory in the Tomcat installation where
    # servlets, libraries and configuration files can be installed
    tomcat: /usr/share/tomcat
    marmotta_home: "{{ project_base }}/marmotta"
    solr_context: hydra
    solr_home: "{{ project_base }}/solr"

    contact_email: "{{ lookup('env', 'EMAIL') }}"

    # SMTP
    smtp_address: sendmail-relay-2476.library.ucsb.edu
    smtp_port: 25
    smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
    # leave blank
    smtp_domain:
    smtp_pass:

    file_server: "://svmwindows.library.ucsb.edu/repository"
    mount_point: "{{ project_base }}/ingest"
    mount_opts: -fstype=cifs,ro,sec=ntlm,noexec,_netdev

  roles:
    - { role: '../provisioning/centos/roles/housekeeping', become: yes }
    - { role: '../provisioning/centos/roles/ruby' }
    - { role: '../provisioning/centos/roles/services' }
    - { role: '../provisioning/centos/roles/hydra-stack' }
    - { role: '../provisioning/centos/roles/ffmpeg' }
    - { role: '../provisioning/centos/roles/imagemagick' }
    - { role: '../provisioning/centos/roles/passenger', become: yes }
    - { role: '../provisioning/centos/roles/marmotta' }
    - { role: '../provisioning/centos/roles/app-config', become: yes }
    - { role: '../provisioning/centos/roles/ezid' }
    - { role: '../provisioning/centos/roles/smtp' }
    - { role: '../provisioning/centos/roles/ldap' }
    - { role: '../provisioning/centos/roles/riiif' }
    - { role: '../provisioning/centos/roles/hostname' }
    - { role: '../provisioning/centos/roles/automount' }
    - { role: alexandria-v2, become: yes }
